name: ci

on:
  push:
#     tags:
#       - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/*/}

      - name: push change
        env:
          TEST: ${{ secrets.Test }}
        run: |
          printenv

    
